### ISSUE TITLE
Add more messages/notifications for the player

### ISSUE THREAD

**Issue by metoxys** [E66666666/GTAVGhostReplay#3]
For instance, something like "Recording started" when the run starts.

So far the only way for this mod to communicate (outside of its menu) that a run is ongoing is spawning the ghost if there is one selected - giving the player more feedback when something is happening greatly improves the first time experience and flattens the learning curve.

Maybe also a message when the ghost finishes the run in case it finishes before the player does.

**Comment by E66666666** [comment]
If the player doesn't grasp the concept of "cross line = lap starts" they might need to see a brain doctor.

Anyway, lap times are enough information.
