### ISSUE TITLE
Add option to disable stunt jumps while recording a run

### ISSUE THREAD

**Issue by metoxys** [E66666666/GTAVGhostReplay#4]
Fairly self-explanatory

Toggle should disable stunt jumps (camera change, slowdown, sound effects) - or maybe even just set this behavior as the standard without a toggle

Of course there is a way to get around stunt jumps in singleplayer (by aiming) but it'd be cool to have this happen automatically

**Comment by E66666666** [comment]
Doesn't seem like there's an easy fix, and I'm not gonna let it monitor and cancel the stunt jumps, or make it disable any stunt jumps.

Use a separate mod for that, if any even exists.
