### ISSUE TITLE
Deleting saved runs is very unsafe and can lead to false deletions

### ISSUE THREAD

**Issue by metoxys** [E66666666/GTAVGhostReplay#6]
Scenario, I had the following saved runs on a track:
- Penetrator  
- Penumbra FF  
- Huntley S  
- Huntley S  
- Huntley S
- Drift Yosemite

I use the `left arrow` key to delete one of the Huntley S laptimes. What happens is that the Penumbra FF laptime ended up deleted. even though only the Huntley S replay in question was selected.

**Comment by E66666666** [comment]
Could you provide an actual example, with the log and what file you want to delete, and which actually got deleted, along with a log?

Had this issue but couldn't reproduce it, but if it keeps happening I'll just nuke the delete functionality.

**Comment by metoxys** [comment]
In retrospect, it turns out that the files were left intact on the drive (is it because I used a symbolic link for the GhostReplay folder?)

I proceeded to delete the files themselves from the explorer, but I would personally nuke the delete functionality or at least add an option to disable it (to avoid panic in the user)

**Comment by E66666666** [comment]
... don't place files weirdly.
